nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['^https://.*\.vercel\.app$']
        allow_methods: ['GET', 'POST', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: []
        max_age: 3600
        allow_credentials: false
    paths:
        '^/newMessage':
            allow_origin: ['https://paulinas-portfolio.vercel.app']
