nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['https://portfolio-svelte-kit-rose\.vercel\.app/?']
        allow_methods: ['GET', 'OPTIONS', 'POST']
        allow_headers: ['Content-Type']
        max_age: 3600
    paths:
        '^/newMessage': ~
