version: 0.2

env:
    variables:
        APP_ENV: test
        DATABASE_URL: "sqlite:///:memory:"
        MESSENGER_TRANSPORT_DSN: "in-memory://"
        MAILER_DSN: "null://default"
        SECRET: "dummysecret"

phases:
    install:
        runtime-versions:
            php: 8.2
        commands:
            - echo Installing Composer dependencies...
            - composer install --no-interaction --prefer-dist --optimize-autoloader --no-scripts

    pre_build:
        commands:
            - echo Running PHPUnit tests...
            - php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
            - php bin/phpunit -c phpunit.dist.xml

    build:
        commands:
            - echo Clearing cache for production...
            - APP_ENV=prod DATABASE_URL=mysql://user:pass@host/db MESSENGER_TRANSPORT_DSN=doctrine://default MAILER_DSN=null://default php bin/console cache:clear --no-warmup
            - echo Production build finished

artifacts:
    files:
        - '**/*'
    discard-paths: no
