version: 0.2

env:
    variables:
        # Miljövariabler som används under hela builden
        APP_ENV: test
        DATABASE_URL: "sqlite:///:memory:"
        MESSENGER_TRANSPORT_DSN: "in-memory://"
        MAILER_DSN: null://default
        SECRET: dummysecret

phases:
    install:
        runtime-versions:
            php: 8.2
        commands:
            - echo "Installing Composer dependencies..."
            - composer install --no-interaction --prefer-dist --optimize-autoloader --no-scripts

    pre_build:
        commands:
            - echo Creating test environment...
            - export APP_ENV=test
            - export DATABASE_URL="sqlite:///:memory:"
            - export MESSENGER_TRANSPORT_DSN="in-memory://"
            - export MAILER_DSN="null://default"
            - export SECRET="dummysecret"
            - echo Running tests...
            - php bin/phpunit -c phpunit.dist.xml

    build:
        commands:
            - echo "Clearing cache for production..."
            - APP_ENV=prod DATABASE_URL=mysql://user:pass@host/db MESSENGER_TRANSPORT_DSN=doctrine://default MAILER_DSN=null://default php bin/console cache:clear --no-warmup
            - echo "Build finished."

artifacts:
    files:
        - '**/*'
    discard-paths: no
