version: 0.2
phases:
    install:
        commands:
            - composer install --no-interaction --prefer-dist --optimize-autoloader --no-scripts
    build:
        commands:
            - zip -r myapp.zip .
artifacts:
    files:
        - myapp.zip
